---
code_indent: "  "
collections: 
  api: { output: true, permalink: "/:collection/:path/", title: "API" }
  examples: { output: true, permalink: "/:collection/:path/", title: "Examples" }
  guides: { output: true, permalink: "/:collection/:path/", title: "Guides" }
compress_html: 
  comments: [ "<!-- ", " -->" ]
example_root: "/examples"
guide_root: "/guides"
highlighter: "rouge"
module_root: "/api"
permalink: "pretty"
project: 
  name: "lsdoc"
  owner: "pixeldroid"
  repo: "https://github.com/pixeldroid/lsdoc"
  version: "1.0.0"
sass: 
  style: "compressed"
template_version: "9.9.9"